# values-codecentric.yaml
keycloak:
  username: smap
  password: smap
  
  # PostgreSQL inclus
  postgresql:
    enabled: true
    postgresqlUsername: bn_keycloak
    postgresqlPassword: bn_keycloak
    postgresqlDatabase: bitnami_keycloak
  
  # Ou utiliser une DB externe
  # externalDatabase:
  #   host: postgresql
  #   port: 5432
  
  ingress:
    enabled: true
    className: "kong"
    hostname: keycloak.example.com

  # Ressources
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"