# values-lenity.yaml
global:
  # Lenity utilise souvent des images depuis leur registry
  imageRegistry: "registry.lenity.io"

keycloak:
  enabled: true
  auth:
    adminUser: smap
    adminPassword: smap
  
  # Lenity a souvent une configuration différente
  # Vérifie leur documentation
  postgresql:
    enabled: true
    auth:
      username: keycloak
      password: "bn_keycloak"
      database: keycloak
  
  ingress:
    enabled: true
    className: "kong"
    hosts:
      - keycloak.example.com