image:
  repository: quay.io/keycloak/keycloak
  tag: "24.0.1"

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start-dev"

auth:
  adminUser: admin
  adminPassword: admin

proxy: edge

http:
  relativePath: /auth

postgresql:
  enabled: true
  auth:
    username: keycloak
    password: keycloak
    database: keycloak
