apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-proxy
  namespace: ingress
spec:
  ingressClassName: traefik
  rules:
  - host: kong-dev.ingress.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-app-kong-proxy
            port:
              number: 8000
