apiVersion: v1
kind: ConfigMap
metadata:
  name: kong
  namespace: ingress
data:
  kong.yml: |
    _format_version: "3.0"

    services:
      - name: echo-service
        url: http://example.com
        routes:
          - name: example-routes
            paths:
              - /echo  

