image:
  repository: kong
  tag: "3.9"

env:
  database: "off"
  nginx_worker_processes: "1"
  KONG_LOG_LEVEL: notice
  KONG_DECLARATIVE_CONFIG: /kong_dbless/kong.yml
  admin_gui_url: "http://34.154.111.227:8002"


proxy:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    nodePort: 30081

admin:
  enabled: true
  type: ClusterIP

ingressController:
  enabled: true
  installCRDs: true

plugins:
  configMaps: []
  secrets: []

extraVolumes:
  - name: kong-dbless-config
    configMap:
      name: kong
      items:
        - key: kong.yml
          path: kong.yml

extraVolumeMounts:
  - name: kong-dbless-config
    mountPath: /kong_dbless
    readOnly: true
