apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: ingress
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: echo-service
        url: http://echo.default.svc.cluster.local:80
        routes:
          - name: echo-route
            paths:
              - /echo
          - name: hello.route
            paths:
              - /hello    

    consumers:
      - username: inventory-service
        custom_id: inventory

    jwt_secrets:
      - consumer: inventory-service
        key: inventory-issuer
        secret: super-secret-key
        algorithm: HS256       