apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: ingress
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: echo-service
        url: http://keycloak-http.smap.svc.cluster.local:80
        routes:
          - name: echo-route
            paths:
              - /echo
          - name: hello.route
            paths:
              - /hello
        plugins:
          - name: jwt
            config:
              secret_is_base64: false
              run_on_preflight: true
              key_claim_name: iss
              claims_to_verify:
                - exp

          - name: inject-admin-token
            config:
              token_url: http://keycloak-http.smap.svc.cluster.local:80/realms/master/protocol/openid-connect/token       

      - name: logging-service
        url: http://keycloak-http.smap.svc.cluster.local:80
        routes:
          - name: logging-route
            methods:
              - POST
            paths:
              - /logging/v1
            strip_path: false  

            plugins:
              - name: inject-admin-token
                config:
                  token_url: http://keycloak-http.smap.svc.cluster.local:80/realms/master/protocol/openid-connect/token       
                          

    consumers:
      - username: inventory-service
        custom_id: inventory

    jwt_secrets:
      - consumer: inventory-service
        key: inventory-issuer
        secret: super-secret-key
        algorithm: HS256       