apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: smap
  sources:
    - repoURL: https://codecentric.github.io/helm-charts
      chart: keycloak
      targetRevision: 18.4.3
      helm:
        valueFiles:
          - values.yaml
          - $customValues/platform/keycloak/values.yaml
    - repoURL: "https://github.com/tomeko19/smap-platform.git"
      targetRevision: dev
      ref: customValues
      directory:
        recurse: false    
  destination:
    server: https://kubernetes.default.svc
    namespace: smap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2  